# Generated by Django 5.0.2 on 2026-02-09 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('work_day', models.CharField(blank=True, max_length=100, null=True)),
                ('work_time', models.CharField(blank=True, max_length=100, null=True)),
                ('cooperation_type', models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('remote', 'Remote'), ('project', 'Project-Based')], max_length=20)),
                ('work_indicators', models.TextField(help_text='List of skills or requirements')),
                ('job_explanation', models.TextField(help_text='Detailed description of the job')),
                ('age_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joboffers.jobcategory')),
                ('manager', models.ForeignKey(limit_choices_to={'role__name': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffers.jobposition')),
            ],
        ),
    ]
