# Generated by Django 5.0.2 on 2025-11-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('joboffers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('employee_first_name', models.CharField(max_length=50)),
                ('employee_last_name', models.CharField(max_length=50)),
                ('requested_salary', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('checking', 'Checking'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='checking', max_length=20)),
                ('request_check', models.CharField(choices=[('checked', 'Checked'), ('not_checked', 'Not Checked')], default='not_checked', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_requests', to='Account.personalinformation')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='joboffers.joboffer')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='joboffers.jobposition')),
            ],
        ),
    ]
