# Generated by Django 5.0.2 on 2025-12-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('living_city', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_job', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='Account.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Account.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100)),
                ('level', models.CharField(help_text='Example: Beginner / Intermediate / Expert', max_length=50)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='software_skills', to='Account.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='StudyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grade_of_study', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='study_history', to='Account.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resume', to='Account.personalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=100)),
                ('work_position', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(limit_choices_to={'role__name': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='Account.personalinformation')),
            ],
        ),
    ]
